#!/bin/bash

# yifengyou: 打开全局调试，默认不建议打开，信息太大
# set -x
#
# Copyright (c) 2013-2021 Igor Pecovnik, igor.pecovnik@gma**.com
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the Armbian build script
# https://github.com/armbian/build/

# DO NOT EDIT THIS FILE
# use configuration files like config-default.conf to set the build configuration
# check Armbian documentation https://docs.armbian.com/ for more info

# yifengyou: realpath 获取给定文件/目录的绝对路径
# yifengyou: dirname 获取给定文件/目录的父路径
SRC="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# check for whitespace in ${SRC} and exit for safety reasons
# yifengyou: 匹配空格
grep -q "[[:space:]]" <<< "${SRC}" && {
	echo "\"${SRC}\" contains whitespace. Not supported. Aborting." >&2
	exit 1
}

cd "${SRC}" || exit

if [[ -f "${SRC}"/lib/import-functions.sh ]]; then
	# yifengyou: 工作目录已经存在.git目录，就会出现这个问题，其实是git安全加固，此处直接简单粗暴绕过
	# Declare this folder as safe
	if ! grep -q "directory = \*" "$HOME/.gitconfig" 2> /dev/null; then
		git config --global --add safe.directory "*"
	fi

	# shellcheck source=lib/import-functions.sh
	source "${SRC}"/lib/import-functions.sh

else

	echo "Error: missing build directory structure"
	echo "Please clone the full repository https://github.com/armbian/build/"
	exit 255

fi

# yifengyou: lib\functions\cli\cli-entrypoint.sh
cli_entrypoint "$@"
